### PR TITLE
Wrote tests for server and for app. An empty error div is now rendere…

### PR DESCRIPTION
**Pull request by howardyang25**
…d if no images are found in the database.

A lot of testing, mocking, and error handling in this PR. I had to write my mocks in such a way that they could either resolve or reject. I don't know if this is the ideal way to achieve 100% test coverage, so I may refactor in the future. 

The only new feature that was implemented was that a blank ErrorDiv is now displayed instead of the Gallery if no images are found in the database. 

Screen Shot 2019-08-28 at 2 49 06 PM

### CODE REVIEW

**Comment by ez-li** [comment]
Oh I see. Yes we will have to make a 404 page for restaurants not in the system. I meant for this part of your rendering:
const getImages = (rid, cb) => {
  if (rid > 100) {
you shouldn't have a condition on rid > 100? but rather run the cb on the restaurant to search for images in the db regardless of the name? and as you said, if it's not there it returns empty array or null which is fine.

**Comment by howardyang25** [comment]
The code you are referencing is in my mock function, so it's only being called in the test. I hardcoded a few rids to force an error just so I could test those branches in my code. 

I changed it in the previous commit:

const getImages = (rid, cb) => {
  if (rid === 'willThrowError') {
    cb('Unknown error');
  }

  cb(null, sampleResponseData);
};

My actual code will query the database for any restaurant name that is type into the url.

**Comment by ez-li** [comment]
Got it! Thank you for the clarification.

**Comment by howardyang25** [comment]
Thanks for the back-and-forth! It helped me think more about my code and clean things up.

**Pull request merged**
